### ISSUE TITLE
封装工具类收件人越来越多BUG

### ISSUE THREAD

**Issue by SpringStudent** [biezhi/oh-my-email#7]
![image](https://user-images.githubusercontent.com/14833956/32091001-d2423ec0-bb24-11e7-8a8e-5fff69382762.png)
工具类代码如下
![image](https://user-images.githubusercontent.com/14833956/32091039-fe12dc30-bb24-11e7-869e-75c0dd432ea9.png)
多次使用工具类，收件人会越来越多

**Comment by SpringStudent** [comment]
应该改为set方法才对

**Comment by andylizi** [comment]
实际上问题的关键在于 `msg` 字段根本不应该是 static 的。这样会导致所有创建的 `OhMyEmail` 邮件实例全都共享一个 `MimeMessage` 对象。

解决办法可以参考我的 Fork [andylizi/oh-my-email 中的 `java8` 分支](https://github.com/andylizi/oh-my-email/blob/java8/src/main/java/io/github/biezhi/ome/OhMyEmail.java)。
因为项目作者看起来想让这个项目支持 Java 8 以下，而我的修改版/修复版用了 Java 8 的 API，因此我没有将我的版本 PR 上来。

**Comment by SpringStudent** [comment]
这里改成set方法即可
![image](https://user-images.githubusercontent.com/14833956/32098457-59b83818-bb3f-11e7-8486-021683456b1e.png)

**Comment by andylizi** [comment]
治标不治本。仍然会出现其他的冲突。
