### ISSUE TITLE
请问添加subject的时候报空指针怎么破?

### ISSUE THREAD

**Issue by qq727127158** [biezhi/oh-my-email#9]
java.lang.NullPointerException
	at io.github.biezhi.ome.OhMyEmail.subject(OhMyEmail.java:75)

**Comment by biezhi** [comment]
新版本可否重现？

**Comment by zhangchiisgy** [comment]
没有遇到这个问题

在 2017-12-13 23:26:10，"王爵nice" <notifications@github.com> 写道：


新版本可否重现？
